import pandas as pd
import numpy as np
df = pd.read_csv("D:/py revision/archive - Copy/dataset.csv")
df.info()
df.head()
describe_df = df.describe()
print(describe_df)
print(describe_df.columns)
print(describe_df.index)
print(describe_df.values)
print(describe_df.dtypes)
print(describe_df.shape)
print(describe_df.size)
print(describe_df.ndim)
print(describe_df.nbytes)
print(describe_df.nrows)
print(describe_df.ncols)
quantile_df = df.quantile()
print(quantile_df)